### ISSUE TITLE
[Enhancement] Add menu entry

### ISSUE THREAD

**Issue by 011V32** [t0bst4r/home-assistant-addons#2] opened 2024-11-08 07:29 UTC
Hello.
It would be great if the Matter Bridge got its own menu entry in HA.
(RaspberryMatic already does this as a reference.)
Thanks for your great work!

**Comment by t0bst4r** [comment] 2024-11-16 19:15
This is a duplicate of: https://github.com/t0bst4r/home-assistant-matter-hub/issues/36

**Closed by t0bst4r** 2024-11-16 19:15 UTC
